// LES TYPES D ACTIONS

// - EPISODES
export const GET_EPISODES_REQUEST: 'GET_EPISODES_REQUEST' =
  'GET_EPISODES_REQUEST';
export const GET_EPISODES_SUCCESS: 'GET_EPISODES_SUCCESS' =
  'GET_EPISODES_SUCCESS';
export const GET_EPISODES_FAILED: 'GET_EPISODES_FAILED' = 'GET_EPISODES_FAILED';
export const SET_SELECTED_EPISODE: 'SET_SELECTED_EPISODE' =
  'SET_SELECTED_EPISODE';
